name: Dapr Component | Build Image

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ca-central-1
  ECR_REPO_BASE: 122610481075.dkr.ecr.ca-central-1.amazonaws.com
  AWS_ROLE_TO_ASSUME: arn:aws:iam::122610481075:role/GithubActionsDaprRole
  EKS_CLUSTER_NAME: dapr-cluster-canada
  KUBERNETES_NAMESPACE: default
  SERVICE_NAME: datetime
  ECR_REPOSITORY_NAME: dapr-datetime

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ github.sha }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Run Tests
      #   if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_tests }}
      #   uses: ./.github/workflows/ci.yml
      #   with:
      #     service: checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.ECR_REPO_BASE }}/${{ env.ECR_REPOSITORY_NAME }}:latest,${{ env.ECR_REPO_BASE }}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GH_PACKAGES_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Docker image
        run: |
          echo "Verifying Docker image exists in ECR..."
          aws ecr describe-images --repository-name ${{ env.ECR_REPOSITORY_NAME }} --image-ids imageTag=latest imageTag=${{ github.sha }} || (echo "Docker image not found in ECR" && exit 1)
  