name: Deploy support

on:
  push:
    branches:
      - main
    paths:
      - "components/support/**"
      - "packages/brain-sdk/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/deploy-component.yml"
      - ".github/workflows/deploy-support.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-component.yml
    with:
      component_name: support
      component_path: components/support
    secrets: inherit
